import type { DocumentInputs, MergedDocument } from "../types/documentTypes";

function substitutePlaceholders(text: string, inputs: DocumentInputs): string {
  return text
    .replace(/\{\{businessName\}\}/g, inputs.businessName || "[Business Name]")
    .replace(/\{\{websiteUrl\}\}/g, inputs.websiteUrl || "[Website URL]")
    .replace(/\{\{contactEmail\}\}/g, inputs.contactEmail || "[Contact Email]");
}

const LEGAL_DISCLAIMER_SECTION = {
  id: "legal-disclaimer",
  title: "Important Legal Disclaimer",
  content:
    "This document was generated by PrivacyLaw AutoGen as a template for informational purposes only. It does NOT constitute legal advice and should not be relied upon as such. Laws vary by jurisdiction and change over time. You should consult a qualified data protection lawyer or legal counsel to review this document before publishing it on your website or using it in your business operations. PrivacyLaw AutoGen and its operators accept no liability for any use of this generated document.",
};

export function generateCookiePolicy(inputs: DocumentInputs): MergedDocument {
  const hasAnalytics =
    inputs.analyticsProvider &&
    inputs.analyticsProvider !== "none" &&
    inputs.analyticsProvider !== "";
  const isGoogleAnalytics = inputs.analyticsProvider
    ?.toLowerCase()
    .includes("google");
  const isMetaPixel =
    inputs.analyticsProvider?.toLowerCase().includes("meta") ||
    inputs.analyticsProvider?.toLowerCase().includes("facebook");

  const sections = [
    LEGAL_DISCLAIMER_SECTION,
    {
      id: "cookie-1",
      title: "1. What Are Cookies",
      content: substitutePlaceholders(
        "Cookies are small text files that are placed on your device when you visit a website. They are widely used to make websites work more efficiently and to provide information to website owners. {{businessName}} uses cookies on {{websiteUrl}} to enhance your browsing experience.",
        inputs,
      ),
    },
    {
      id: "cookie-2",
      title: "2. Types of Cookies We Use",
      content:
        "We use the following types of cookies:\n\n**Strictly Necessary Cookies**: These cookies are essential for the website to function properly. They enable core functionality such as security, network management, and accessibility. You cannot opt out of these cookies.\n\n**Functional Cookies**: These cookies allow us to remember choices you make and provide enhanced, more personal features.\n\n**Performance/Analytics Cookies**: These cookies collect information about how visitors use our website, such as which pages are visited most often.\n\n**Marketing/Targeting Cookies**: These cookies are used to deliver advertisements more relevant to you and your interests.",
    },
    {
      id: "cookie-3",
      title: "3. Necessary Cookies",
      content:
        "The following necessary cookies are used on our website:\n\n| Cookie Name | Purpose | Duration |\n|-------------|---------|----------|\n| session_id | Maintains your session | Session |\n| csrf_token | Security protection | Session |\n| cookie_consent | Stores your cookie preferences | 1 year |",
    },
    ...(hasAnalytics
      ? [
          {
            id: "cookie-4",
            title: "4. Analytics Cookies",
            content: isGoogleAnalytics
              ? "We use Google Analytics to understand how visitors interact with our website. Google Analytics uses the following cookies:\n\n| Cookie Name | Purpose | Duration |\n|-------------|---------|----------|\n| _ga | Distinguishes users | 2 years |\n| _ga_* | Maintains session state | 2 years |\n| _gid | Distinguishes users | 24 hours |\n| _gat | Throttles request rate | 1 minute |\n\nGoogle Analytics data is processed by Google LLC. For more information, see Google's Privacy Policy at https://policies.google.com/privacy."
              : isMetaPixel
                ? "We use Meta Pixel (formerly Facebook Pixel) to measure the effectiveness of our advertising and to understand how visitors interact with our website. Meta Pixel uses the following cookies:\n\n| Cookie Name | Purpose | Duration |\n|-------------|---------|----------|\n| _fbp | Identifies browsers | 3 months |\n| fr | Advertising delivery | 3 months |\n| datr | Browser identification | 2 years |\n\nMeta Pixel data is processed by Meta Platforms, Inc. For more information, see Meta's Privacy Policy at https://www.facebook.com/privacy/policy/."
                : `We use ${inputs.analyticsProvider} for analytics purposes to understand how visitors use our website. Analytics cookies help us improve our services by collecting information about usage patterns.`,
          },
        ]
      : []),
    {
      id: "cookie-5",
      title: `${hasAnalytics ? "5" : "4"}. Third-Party Cookies`,
      content: substitutePlaceholders(
        "Some cookies on our website are set by third-party services. These third parties may use cookies to track your browsing activity across different websites. We do not control these third-party cookies. Please refer to the respective third-party privacy policies for more information.",
        inputs,
      ),
    },
    {
      id: "cookie-6",
      title: `${hasAnalytics ? "6" : "5"}. Cookie Consent and Control`,
      content: substitutePlaceholders(
        "When you first visit {{websiteUrl}}, you will be presented with a cookie consent banner. You can choose to accept all cookies, reject non-essential cookies, or customize your preferences. You can change your cookie preferences at any time by clearing your browser cookies and revisiting our website.",
        inputs,
      ),
    },
    {
      id: "cookie-7",
      title: `${hasAnalytics ? "7" : "6"}. Cookie Retention Period`,
      content:
        "Cookies are retained for varying periods depending on their type:\n\n• Session cookies: Deleted when you close your browser\n• Persistent cookies: Retained for the period specified in the cookie (typically 1–2 years)\n• Third-party cookies: Retention periods are set by the respective third parties",
    },
    {
      id: "cookie-8",
      title: `${hasAnalytics ? "8" : "7"}. How to Manage Cookies`,
      content:
        'You can control and manage cookies in several ways:\n\n• **Browser Settings**: Most browsers allow you to refuse or delete cookies. Visit your browser\'s help section for instructions.\n• **Opt-Out Tools**: For Google Analytics, visit https://tools.google.com/dlpage/gaoptout\n• **Do Not Track**: Some browsers support a "Do Not Track" feature\n\nPlease note that disabling cookies may affect the functionality of our website.',
    },
    {
      id: "cookie-9",
      title: `${hasAnalytics ? "9" : "8"}. Contact Us`,
      content: substitutePlaceholders(
        "If you have any questions about our use of cookies, please contact us at:\n\n{{businessName}}\nEmail: {{contactEmail}}\nWebsite: {{websiteUrl}}",
        inputs,
      ),
    },
  ];

  return {
    title: "Cookie Policy",
    effectiveDate: new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    sections,
    frameworkName: "Cookie Policy",
    frameworkVersion: "1.0.0",
    lastReviewed: new Date().toISOString().split("T")[0],
  };
}
