import type { DocumentInputs, MergedDocument } from "../types/documentTypes";

function substitutePlaceholders(text: string, inputs: DocumentInputs): string {
  const jurisdictionMap: Record<string, string> = {
    DE: "Germany",
    FR: "France",
    IT: "Italy",
    ES: "Spain",
    GB: "England and Wales",
    IN: "India",
    US: "California, USA",
    CA: "Ontario, Canada",
    AU: "New South Wales, Australia",
    NL: "Netherlands",
    BE: "Belgium",
    SE: "Sweden",
  };
  const jurisdiction =
    jurisdictionMap[inputs.selectedCountry] || "your jurisdiction";

  return text
    .replace(/\{\{businessName\}\}/g, inputs.businessName || "[Business Name]")
    .replace(/\{\{websiteUrl\}\}/g, inputs.websiteUrl || "[Website URL]")
    .replace(/\{\{contactEmail\}\}/g, inputs.contactEmail || "[Contact Email]")
    .replace(/\{\{jurisdiction\}\}/g, jurisdiction);
}

const LEGAL_DISCLAIMER_SECTION = {
  id: "legal-disclaimer",
  title: "Important Legal Disclaimer",
  content:
    "This document was generated by PrivacyLaw AutoGen as a template for informational purposes only. It does NOT constitute legal advice and should not be relied upon as such. Laws vary by jurisdiction and change over time. You should consult a qualified data protection lawyer or legal counsel to review this document before publishing it on your website or using it in your business operations. PrivacyLaw AutoGen and its operators accept no liability for any use of this generated document.",
};

export function generateToSDocument(inputs: DocumentInputs): MergedDocument {
  const sections = [
    LEGAL_DISCLAIMER_SECTION,
    {
      id: "tos-1",
      title: "1. Acceptance of Terms",
      content: substitutePlaceholders(
        'By accessing or using the services provided by {{businessName}} at {{websiteUrl}} ("Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Services.',
        inputs,
      ),
    },
    {
      id: "tos-2",
      title: "2. Description of Services",
      content: substitutePlaceholders(
        "{{businessName}} provides services as described on our website at {{websiteUrl}}. We reserve the right to modify, suspend, or discontinue any part of our Services at any time with or without notice.",
        inputs,
      ),
    },
    {
      id: "tos-3",
      title: "3. User Accounts",
      content: substitutePlaceholders(
        "To access certain features of our Services, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify {{businessName}} immediately of any unauthorized use of your account at {{contactEmail}}.",
        inputs,
      ),
    },
    {
      id: "tos-4",
      title: "4. Acceptable Use",
      content:
        "You agree not to use our Services to:\n\n• Violate any applicable laws or regulations\n• Infringe upon the rights of others\n• Transmit harmful, offensive, or illegal content\n• Attempt to gain unauthorized access to our systems\n• Engage in any activity that disrupts or interferes with our Services\n• Use automated tools to scrape or extract data without permission",
    },
    {
      id: "tos-5",
      title: "5. Intellectual Property",
      content: substitutePlaceholders(
        "All content, features, and functionality of our Services, including but not limited to text, graphics, logos, and software, are the exclusive property of {{businessName}} and are protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written permission.",
        inputs,
      ),
    },
    {
      id: "tos-6",
      title: "6. User Content",
      content: substitutePlaceholders(
        "By submitting content to our Services, you grant {{businessName}} a non-exclusive, worldwide, royalty-free license to use, reproduce, and display such content in connection with providing our Services. You represent that you have all necessary rights to grant this license.",
        inputs,
      ),
    },
    {
      id: "tos-7",
      title: "7. Privacy",
      content: substitutePlaceholders(
        "Your use of our Services is also governed by our Privacy Policy, available at {{websiteUrl}}. By using our Services, you consent to the collection and use of your information as described in our Privacy Policy.",
        inputs,
      ),
    },
    {
      id: "tos-8",
      title: "8. Disclaimer of Warranties",
      content: substitutePlaceholders(
        'OUR SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. {{businessName}} DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.',
        inputs,
      ),
    },
    {
      id: "tos-9",
      title: "9. Limitation of Liability",
      content: substitutePlaceholders(
        "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, {{businessName}} SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF OUR SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
        inputs,
      ),
    },
    {
      id: "tos-10",
      title: "10. Governing Law",
      content: substitutePlaceholders(
        "These Terms shall be governed by and construed in accordance with the laws of {{jurisdiction}}, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of {{jurisdiction}}.",
        inputs,
      ),
    },
    {
      id: "tos-11",
      title: "11. Dispute Resolution",
      content: substitutePlaceholders(
        "Before initiating any formal legal proceedings, you agree to first contact {{businessName}} at {{contactEmail}} to attempt to resolve the dispute informally. If the dispute cannot be resolved within 30 days, either party may pursue formal legal remedies.",
        inputs,
      ),
    },
    {
      id: "tos-12",
      title: "12. Changes to Terms",
      content: substitutePlaceholders(
        'We reserve the right to modify these Terms at any time. We will notify you of significant changes by posting the new Terms on our website at {{websiteUrl}} and updating the "Last Updated" date. Your continued use of our Services after such changes constitutes your acceptance of the new Terms.',
        inputs,
      ),
    },
    {
      id: "tos-13",
      title: "13. Termination",
      content: substitutePlaceholders(
        "{{businessName}} reserves the right to terminate or suspend your access to our Services at any time, with or without cause, with or without notice. Upon termination, your right to use the Services will immediately cease.",
        inputs,
      ),
    },
    {
      id: "tos-14",
      title: "14. Contact Information",
      content: substitutePlaceholders(
        "If you have any questions about these Terms, please contact us at:\n\n{{businessName}}\nEmail: {{contactEmail}}\nWebsite: {{websiteUrl}}",
        inputs,
      ),
    },
  ];

  return {
    title: "Terms of Service",
    effectiveDate: new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    sections,
    frameworkName: "Terms of Service",
    frameworkVersion: "1.0.0",
    lastReviewed: new Date().toISOString().split("T")[0],
  };
}
