import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import type { MergedDocument } from "@/types/documentTypes";
import { CalendarDays, FileText, Shield } from "lucide-react";
import { DocumentSection } from "./DocumentSection";

interface LivePreviewPanelProps {
  document: MergedDocument;
}

export function LivePreviewPanel({ document: doc }: LivePreviewPanelProps) {
  const reviewDate = doc.lastReviewed
    ? new Date(doc.lastReviewed).toLocaleDateString("en-US", {
        month: "short",
        year: "numeric",
      })
    : null;

  return (
    <div className="flex flex-col h-full">
      {/* Preview header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border/60 bg-muted/30 rounded-t-lg shrink-0">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-primary" />
          <span className="text-sm font-semibold">Live Preview</span>
        </div>
        <div className="flex items-center gap-2 flex-wrap justify-end">
          <Badge
            variant="secondary"
            className="text-xs font-mono px-2 py-0.5 gap-1"
          >
            <Shield className="h-3 w-3" />
            {doc.frameworkName}
            {doc.frameworkVersion && ` v${doc.frameworkVersion}`}
          </Badge>
          {reviewDate && (
            <Badge
              variant="outline"
              className="text-xs px-2 py-0.5 text-muted-foreground"
            >
              <CalendarDays className="h-3 w-3 mr-1" />
              Reviewed {reviewDate}
            </Badge>
          )}
        </div>
      </div>

      {/* Document content */}
      <ScrollArea className="flex-1 rounded-b-lg border border-t-0 border-border/60 bg-card">
        <div className="p-6 legal-document">
          {/* Document title block */}
          <div className="mb-6 pb-4 border-b-2 border-primary/20">
            <h1 className="text-xl font-bold text-foreground mb-1">
              {doc.title}
            </h1>
            <p className="text-sm text-muted-foreground">{doc.frameworkName}</p>
            <div className="flex flex-wrap gap-3 mt-3 text-xs text-muted-foreground">
              <span>Effective: {doc.effectiveDate}</span>
              <span>·</span>
              <span>{doc.frameworkName}</span>
              {doc.frameworkVersion && (
                <>
                  <span>·</span>
                  <span>Version {doc.frameworkVersion}</span>
                </>
              )}
            </div>
            <p className="text-xs text-amber-600 dark:text-amber-400 mt-2 italic">
              ⚠ This is a template document. Please review with a qualified
              legal professional before publishing.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-1">
            {doc.sections.map((section) => (
              <DocumentSection key={section.id} section={section} depth={0} />
            ))}
          </div>

          {/* Footer */}
          <div className="mt-8 pt-4 border-t border-border/40 text-xs text-muted-foreground text-center">
            Generated by PrivacyLaw AutoGen · Template document only · Not legal
            advice
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}
